2022-09-11 16:40:00,049 : INFO : Start of Training
2022-09-11 16:40:00,049 : INFO : Run_id:2022-09-11_164000_931261194
2022-09-11 16:40:00,049 : INFO : Start of Data Load, validation and transformation
2022-09-11 16:40:00,049 : INFO : Start of Archiving Old Rejected Files...
2022-09-11 16:40:00,050 : INFO : End of Archiving Old Rejected Files...
2022-09-11 16:40:00,050 : INFO : Start of Archiving Old Validated Files...
2022-09-11 16:40:00,051 : INFO : End of Archiving Old Validated Files...
2022-09-11 16:40:00,052 : INFO : Start of Archiving Old Processed Files...
2022-09-11 16:40:00,052 : INFO : End of Archiving Old Processed Files...
2022-09-11 16:40:00,052 : INFO : Start of Archiving Old Result Files...
2022-09-11 16:40:00,052 : INFO : End of Archiving Old Result Files...
2022-09-11 16:40:00,053 : INFO : Start of Reading values From Schema...
2022-09-11 16:40:00,053 : INFO : End of Reading values From Schema...
2022-09-11 16:40:00,053 : INFO : Start of Validating Column Length...
2022-09-11 16:40:00,053 : INFO : End of Validating Column Length...
2022-09-11 16:40:00,053 : INFO : Start of Validating Missing Values...
2022-09-11 16:40:00,053 : INFO : End of Validating Missing Values...
2022-09-11 16:40:00,053 : INFO : Start of Replacing Missing Values with NULL...
2022-09-11 16:40:00,053 : INFO : End of Replacing Missing Values with NULL...
2022-09-11 16:40:00,054 : INFO : Start of Creating Table...
2022-09-11 16:40:00,055 : INFO : Opened training database successfully
2022-09-11 16:40:00,055 : INFO : Tables created successfully
2022-09-11 16:40:00,055 : INFO : Closed training database successfully
2022-09-11 16:40:00,055 : INFO : End of Creating Table...
2022-09-11 16:40:00,056 : INFO : Opened training database successfully
2022-09-11 16:40:00,056 : INFO : Start of Inserting Data into Table...
2022-09-11 16:40:00,056 : INFO : End of Inserting Data into Table...
2022-09-11 16:40:00,056 : INFO : Start of Exporting Data into CSV...
2022-09-11 16:40:00,057 : INFO : Opened training database successfully
2022-09-11 16:40:00,058 : INFO : End of Exporting Data into CSV...
2022-09-11 16:40:00,058 : INFO : Start of Moving Processed Files...
2022-09-11 16:40:00,058 : INFO : End of Moving Processed Files...
2022-09-11 16:40:00,058 : INFO : End of Data Load, validation and transformation
2022-09-11 16:40:00,059 : INFO : Start of Preprocessing...
2022-09-11 16:40:00,059 : INFO : Start of reading dataset...
2022-09-11 16:40:00,065 : INFO : End of reading dataset...
2022-09-11 16:40:00,065 : ERROR : Unsuccessful End of Preprocessing...
Traceback (most recent call last):
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 120, in preprocess_trainset
    self.X_ros, self.y_ros = ros.fit_resample(self.X, self.y)
AttributeError: 'Preprocessor' object has no attribute 'X'
2022-09-11 16:40:00,066 : ERROR : Unsuccessful End of Training
Traceback (most recent call last):
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 120, in preprocess_trainset
    self.X_ros, self.y_ros = ros.fit_resample(self.X, self.y)
AttributeError: 'Preprocessor' object has no attribute 'X'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\training\train_model.py", line 27, in training_model
    self.X, self.y = self.preProcess.preprocess_trainset()
  File "C:\Users\napol\PycharmProjects\rappipaychallenge\apps\preprocess\preprocessor.py", line 133, in preprocess_trainset
    raise Exception
Exception
